[package]
name = "_24_swap-nodes-in-pairs"
version = "0.1.0"
authors = ["suhanyujie <suhanyu@bjx.cloud>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
